name: charts_common
version: 1.0.0
description: A common library for charting packages.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  intl: ^0.17.0
  logging: ^1.0.1
  meta: ^1.3.0
  vector_math: ^2.1.0

dev_dependencies:
  mockito: ^5.0.7
  test: ^1.17.3
